[project]
name = "interactive-marimo-notebook"
version = "1.0.0"
description = "Tower app that runs an intractive Marimo notebook."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
    "marimo>=0.14.17",
    "matplotlib>=3.10.5",
    "uvicorn>=0.35.0",
]
